
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author geovani darcie
 */
public class Cifrador extends javax.swing.JFrame {

    final int TAM = 8;
    int totalBytesLidos;
    /**
     * Creates new form Cifrador
     */
    public Cifrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        campo_cifrador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo_cifragem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campo_codigo = new javax.swing.JTextField();
        botao_cifrador = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        decifrar_campo1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        decifrar_campo2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        decifrar_campo3 = new javax.swing.JTextField();
        botao_decifrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imagem_original = new javax.swing.JTextField();
        imagem_water = new javax.swing.JTextField();
        marca_agua = new javax.swing.JTextField();
        botao_water = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        decifrar_water = new javax.swing.JButton();
        decifrar_imagem = new javax.swing.JTextField();
        decifrar_original = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        retirar_marca = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(25, 25, 25));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        campo_cifrador.setBackground(new java.awt.Color(0, 0, 0));
        campo_cifrador.setForeground(new java.awt.Color(204, 204, 204));
        campo_cifrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cifradorActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nome do arquivo original:");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Arquivo para cifragem:");

        campo_cifragem.setBackground(new java.awt.Color(0, 0, 0));
        campo_cifragem.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Chave com 8 digitos:");

        campo_codigo.setBackground(new java.awt.Color(0, 0, 0));
        campo_codigo.setForeground(new java.awt.Color(204, 204, 204));

        botao_cifrador.setBackground(new java.awt.Color(0, 0, 0));
        botao_cifrador.setForeground(new java.awt.Color(204, 204, 204));
        botao_cifrador.setText("Cifrar");
        botao_cifrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cifradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_cifrador, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(campo_cifragem)
                            .addComponent(campo_codigo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botao_cifrador)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_cifrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_cifragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(botao_cifrador)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("Cifrar", jPanel1);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Arquivo cifrado:");

        decifrar_campo1.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_campo1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Arquivo para decifragem:");

        decifrar_campo2.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_campo2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Senha de 8 digitos:");

        decifrar_campo3.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_campo3.setForeground(new java.awt.Color(204, 204, 204));
        decifrar_campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decifrar_campo3ActionPerformed(evt);
            }
        });

        botao_decifrar.setBackground(new java.awt.Color(0, 0, 0));
        botao_decifrar.setForeground(new java.awt.Color(204, 204, 204));
        botao_decifrar.setText("Decifrar");
        botao_decifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_decifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decifrar_campo1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(decifrar_campo2)
                            .addComponent(decifrar_campo3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botao_decifrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(decifrar_campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(decifrar_campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(decifrar_campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botao_decifrar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Decifrar", jPanel4);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Imagem Original:");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Imagem com WaterMarking:");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Marca D agua:");

        imagem_original.setBackground(new java.awt.Color(0, 0, 0));
        imagem_original.setForeground(new java.awt.Color(204, 204, 204));

        imagem_water.setBackground(new java.awt.Color(0, 0, 0));
        imagem_water.setForeground(new java.awt.Color(204, 204, 204));

        marca_agua.setBackground(new java.awt.Color(0, 0, 0));
        marca_agua.setForeground(new java.awt.Color(204, 204, 204));
        marca_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_aguaActionPerformed(evt);
            }
        });

        botao_water.setBackground(new java.awt.Color(0, 0, 0));
        botao_water.setForeground(new java.awt.Color(204, 204, 204));
        botao_water.setText("WaterMarking");
        botao_water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_waterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagem_water, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(imagem_original)
                            .addComponent(marca_agua)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botao_water)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(imagem_original, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(imagem_water, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(marca_agua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_water)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Watermarking", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Imagem com watermarking:");

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Imagem decifrada:");

        decifrar_water.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_water.setForeground(new java.awt.Color(204, 204, 204));
        decifrar_water.setText("Decifrar");
        decifrar_water.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decifrar_waterActionPerformed(evt);
            }
        });

        decifrar_imagem.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_imagem.setForeground(new java.awt.Color(204, 204, 204));

        decifrar_original.setBackground(new java.awt.Color(0, 0, 0));
        decifrar_original.setForeground(new java.awt.Color(204, 204, 204));

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Retirar essa marcaDagua:");

        retirar_marca.setBackground(new java.awt.Color(0, 0, 0));
        retirar_marca.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decifrar_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(decifrar_original)
                            .addComponent(retirar_marca)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(decifrar_water)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(decifrar_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(decifrar_original, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(retirar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decifrar_water)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Decifra Watermarking", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_decifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_decifrarActionPerformed
        String arquivoCifrado;
        char[] arquivoLido = new char[TAM];
        char c = 0;
        int totalLido = 0;

        DataInputStream leitura;

        arquivoCifrado = decifrar_campo1.getText();

        try {

            leitura = new DataInputStream(new FileInputStream(arquivoCifrado));

            do {

                for (int i = 0; i < TAM; i++) {
                    c = (char) leitura.readByte();
                    arquivoLido[i] = c;
                    totalLido = i;
                }

                if (totalLido != 0) {
                    decifrador(arquivoLido);
                }
            } while (c != 0);

            leitura.close();

        } catch (EOFException eof) {

        } catch (IOException e) {

        }
    }//GEN-LAST:event_botao_decifrarActionPerformed

    private void botao_cifradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cifradorActionPerformed
        String arquivoOriginal;
        char[] arquivoLido = new char[TAM];
        char c = 0;
        int totalLido = 0;

        DataInputStream leitura;

        arquivoOriginal = campo_cifrador.getText();

        try {

            leitura = new DataInputStream(new FileInputStream(arquivoOriginal));

            do {

                for (int i = 0; i < TAM; i++) {
                    c = (char) leitura.readByte();
                    arquivoLido[i] = c;
                    totalLido = i;
                }

                if (totalLido != 0) {
                    cifrador(arquivoLido);
                    for (int i = 0; i < TAM; i++) {
                        arquivoLido[i] = ' ';
                    }
                }

            } while (c != 0);

            leitura.close();

        } catch (IOException e) {
            cifrador(arquivoLido);
        }
    }//GEN-LAST:event_botao_cifradorActionPerformed

    private void campo_cifradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cifradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cifradorActionPerformed

    private void marca_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_aguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_aguaActionPerformed

    private void botao_waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_waterActionPerformed
        String imagemOriginal;
        char[] arquivoLido = new char[TAM];
        char c = 0;
        int totalLido = 0;
        

        imagemOriginal = imagem_original.getText();

        DataInputStream leitura;
        try {
            leitura = new DataInputStream(new FileInputStream(imagemOriginal));
            do {
                for (int i = 0; i < TAM; i++) {
                    c = (char) leitura.readByte();
                    arquivoLido[i] = c;
                    totalLido = i;
                    totalBytesLidos +=1;
                }

                if (totalLido != 0) {
                    water(arquivoLido,totalBytesLidos);
                }

            } while (arquivoLido != null);

            leitura.close();

        } catch (IOException e) {
            water(arquivoLido, totalBytesLidos);
        }

    }//GEN-LAST:event_botao_waterActionPerformed

    private void decifrar_waterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decifrar_waterActionPerformed
        String imagemWater;

        char[] arquivoLido = new char[TAM];
        char c = 0;
        int totalLido = 0;

        imagemWater = decifrar_imagem.getText();

        DataInputStream leitura;
        try {
            leitura = new DataInputStream(new FileInputStream(imagemWater));
            do {

                for (int i = 0; i < TAM; i++) {
                    c = (char) leitura.readByte();
                    arquivoLido[i] = c;
                    totalLido = i;
                    totalBytesLidos +=1;
                }

                if (totalLido != 0) {
                    decifrarWater(arquivoLido);
                }

            } while (arquivoLido != null);

            leitura.close();

        } catch (IOException e) {
            decifrarWater(arquivoLido);
        }

    }//GEN-LAST:event_decifrar_waterActionPerformed

    private void decifrar_campo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decifrar_campo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decifrar_campo3ActionPerformed

    public void decifrarWater(char[] arquivoLido) {
        String imagemDecifrada, marcaDagua;
        DataOutputStream escrita;
        int j;

        imagemDecifrada = decifrar_original.getText();
        marcaDagua = retirar_marca.getText();

        //converte
        char[] agua;
        agua = new char[marcaDagua.length()];
        for (int i = 0; i < marcaDagua.length(); i++) {
            agua[i] = marcaDagua.charAt(i);
        }
       
        // escreve
        try {
            j = 0;
            
            if (totalBytesLidos == 16)
            {
              j = j + agua.length;
            }
            escrita = new DataOutputStream(new FileOutputStream(imagemDecifrada, true));
            while (j < TAM) {
             
                escrita.writeByte(arquivoLido[j]);
                j += 1;
                
            }
            escrita.close();
        } catch (IOException e) {

        }

    }

    public void water(char[] arquivoLido, int totalBytesLidos) {
        String imagemWater, waterMarking, marcaDagua;
        DataOutputStream escrita;

        imagemWater = imagem_water.getText();
        marcaDagua = marca_agua.getText();

        //converte
        char[] agua;
        agua = new char[marcaDagua.length()];
        for (int i = 0; i < marcaDagua.length(); i++) {
            agua[i] = marcaDagua.charAt(i);
        }
        
        // escreve
        try {
            escrita = new DataOutputStream(new FileOutputStream(imagemWater, true));
             if (totalBytesLidos == 16)
               {
                 for(int j=0; j<agua.length; j++){  
                 escrita.writeByte(agua[j]);
                 }
               }
            for (int i = 0; i < TAM; i++) {
              
              escrita.writeByte(arquivoLido[i]); 
            }
            escrita.close();
        } catch (IOException e) {

        }

    }

    public void cifrador(char[] arquivoLido) {
        String codigo, arquivoCifrado;
        char[] cifra = new char[TAM];

        DataOutputStream escrita;

        codigo = campo_codigo.getText();
        arquivoCifrado = campo_cifragem.getText();

        //converte
        char[] senha;
        senha = new char[codigo.length()];
        for (int i = 0; i < codigo.length(); i++) {
            senha[i] = codigo.charAt(i);
        }

        //cifra
        for (int i = 0; i < TAM; i++) {

            cifra[i] = (char) (arquivoLido[i] + senha[i]);

        }

        //escrever no arquivo  
        try {
            escrita = new DataOutputStream(new FileOutputStream(arquivoCifrado, true));
            for (int i = 0; i < TAM; i++) {
                escrita.writeByte(cifra[i]);
            }
            escrita.close();
        } catch (IOException e) {

        }
    }

    public void decifrador(char[] arquivoLido) {
        String codigo, arquivoDecifrado;
        char[] decifrado = new char[TAM];

        DataOutputStream escrita;

        codigo = decifrar_campo3.getText();
        arquivoDecifrado = decifrar_campo2.getText();
        //converte
        char[] senha;
        senha = new char[codigo.length()];
        for (int i = 0; i < codigo.length(); i++) {
            senha[i] = codigo.charAt(i);
        }

        //decifra
        for (int i = 0; i < TAM; i++) {

            decifrado[i] = (char) (arquivoLido[i] - senha[i]);
        }

        //escrever no arquivo  
        try {
            escrita = new DataOutputStream(new FileOutputStream(arquivoDecifrado, true));
            for (int i = 0; i < TAM; i++) {
                escrita.writeByte(decifrado[i]);
            }

            escrita.close();
        } catch (IOException e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cifrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cifrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cifrador;
    private javax.swing.JButton botao_decifrar;
    private javax.swing.JButton botao_water;
    private javax.swing.JTextField campo_cifrador;
    private javax.swing.JTextField campo_cifragem;
    private javax.swing.JTextField campo_codigo;
    private javax.swing.JTextField decifrar_campo1;
    private javax.swing.JTextField decifrar_campo2;
    private javax.swing.JTextField decifrar_campo3;
    private javax.swing.JTextField decifrar_imagem;
    private javax.swing.JTextField decifrar_original;
    private javax.swing.JButton decifrar_water;
    private javax.swing.JTextField imagem_original;
    private javax.swing.JTextField imagem_water;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField marca_agua;
    private javax.swing.JTextField retirar_marca;
    // End of variables declaration//GEN-END:variables
}
